### ISSUE TITLE
For some reason, the text is not writing in cutscenes

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#108]
Tested with all characters, text is frozen. Text does fill when spacebar or click is done, and player can still progress.
TextSpeed in options is set to 5.

https://github.com/josephcyang4459/Duo-Darts/assets/65678477/6feb37ff-4e6b-47ec-8361-f8f94e95eb81

**Comment by LipglossBPoppin** [comment]
It was using by default an old value in typewriter effect, and not using the Setting from options this is now changed.
