### ISSUE TITLE
Chad is invisible during his drinking scene

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#121]
https://github.com/josephcyang4459/Duo-Darts/assets/65678477/94b14a9a-9c04-44e3-b1ac-c61c01b5b94a

**Comment by LipglossBPoppin** [comment]
Make sure you Reset your Cutscenes before testing.

![Image](https://github.com/josephcyang4459/Duo-Darts/assets/82534778/9a3b58a9-36f7-4f58-ba0f-c05213320b3a)
