### ISSUE TITLE
Chad does not appear when choosing the default drinking cutscene

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#125]
https://github.com/josephcyang4459/Duo-Darts/assets/65678477/d55bb760-ba70-462a-87da-2822bd622179

**Comment by LipglossBPoppin** [comment]
Check the Cutscene Object to see if it calls an Expression Block if it doesn't then that is stale data, and you need to resend data to cutscenes.

![Image](https://github.com/josephcyang4459/Duo-Darts/assets/82534778/5f20e37c-e695-488a-8dfe-64f98788b57e)

**Comment by LipglossBPoppin** [comment]
I have pushed a fix for stale data on main and all cutscenes and partners should now be correct.

**Comment by LipglossBPoppin** [comment]
Did the fix work, or is this still occuring?

**Comment by LipglossBPoppin** [comment]
Is this fixed yet?

**Comment by josephcyang4459** [comment]
Whoops, sorry for the delay. Thanks for recommenting, I must've missed it in my email feed.

This doesn't appear to be occurring anymore. I'm going to resolve this issue thread since it is no longer occurring.
