### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by vxnkman** [josephcyang4459/Duo-Darts#135]
Two tutorial screens required:
1. Tournament flyer (general)
2. Dart handbook (dart minigame)

**Comment by DatFluffySheep** [comment]
Changed from flyer to invitation and changed handbook to tutorial plaque/poster

Writeups for both are complete and in the production documents.

**Comment by LipglossBPoppin** [comment]
This issue was for writing and art which is now complete as far as I know.
