### ISSUE TITLE
Dartboard 3x dart sometimes does not register

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#140]
It's as name says. When a player hits a 3x area, it sometimes gives the regular score instead of 3x the score. 2x area seems to be fine.

**Comment by LipglossBPoppin** [comment]
This has been an issue for as long as we have been working on it but I did Redo the dart position check I just hadn't set it up so in my next commit this will be fixed.

**Comment by LipglossBPoppin** [comment]
The Game as far as my progress is concerned is now fully onto the new System so this should now be fixed.
