### ISSUE TITLE
When playing darts, sometimes error "Assertion failed" occurs and results in hard crash

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#141]
I'm not too sure what causes this, but so far it's only happened on the player's turn.

**Comment by LipglossBPoppin** [comment]
Has this been replicated? I need more than Assertion Failed.

**Comment by josephcyang4459** [comment]
> Has this been replicated? I need more than Assertion Failed.

Assertion Failed and it being on the player's turn is the things that I gathered. This bug is hard to replicate, it doesn't come up again when I want it to.

It appears to have gone for now. But I'll keep this issue thread open for now.

**Comment by LipglossBPoppin** [comment]
Was this in editor or in the player?

**Comment by josephcyang4459** [comment]
> Was this in editor or in the standalone player?

It was in editor

**Comment by LipglossBPoppin** [comment]
Finally tracked this one down. It is now fixed. 
If the Fire Button was held down when the Player Aim was first enabled, it would crash.
It was a result of having CheckInitialState for the Fire input set to true. It does not need to do an initial state check, so i just set it to false.

![Screenshot 2024-05-22 181601](https://github.com/josephcyang4459/Duo-Darts/assets/82534778/18ca86ec-1963-400c-b7b8-e7d5dcc13fb0)

**Comment by josephcyang4459** [comment]
> Finally tracked this one down. It is now fixed. If the Fire Button was held down when the Player Aim was first enabled, it would crash. It was a result of having CheckInitialState for the Fire input set to true. It does not need to do an initial state check, so i just set it to false.
> 
> ![Screenshot 2024-05-22 181601](https://private-user-images.githubusercontent.com/82534778/332986061-18ca86ec-1963-400c-b7b8-e7d5dcc13fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODk2MTcsIm5iZiI6MTcxNjQ4OTMxNywicGF0aCI6Ii84MjUzNDc3OC8zMzI5ODYwNjEtMThjYTg2ZWMtMTk2My00MDBjLWI3YjgtZTdkNWRjYzEzZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NTU1YWJmOTU1NjM0OWE4NWM4ZDZlZmFmMDJjNDZiMWU4MDQ3Mzc5N2I2ZTE1MGQwYWNhZWViY2U2MWNmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J9gl9EQwBYtAi7YDHr6hDVg3sWyBD_UGsWGNo7xq88Y)
Nice work!
