### ISSUE TITLE
When attempting to exit out of the tutorial screen in story mode, it starts a game of darts with other canvas' active still.

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#142]
https://github.com/josephcyang4459/Duo-Darts/assets/65678477/8bf61bc0-e5e3-45c5-94e2-855847906e38

**Comment by josephcyang4459** [comment]
I'm not too sure where to look to fix this. It looks like the selection of partners is still enabled when viewing the tutorial, which might explain game responsiveness even when in tutorial.

I'm thinking that removing the option to view the tutorial here might be easier. The player already has the option to view the tutorial in the pause menu and the player is forced into the tutorial during their first time playing darts.

**Comment by LipglossBPoppin** [comment]
No it will not be, I was not touching the tutorial or anything in it until it was complete, nor was i going to deal with every issue that i knew full well were an issue in it's current implementation. There are multiple issues with the tutorial system that need to be addressed, and this is just one of them. Try going into story mode, then hitting escape, and then closing the tutorial screen.

**Comment by LipglossBPoppin** [comment]
Specifically the darts tutorial.

**Comment by josephcyang4459** [comment]
That is a good find. I went ahead and made some changes to the tutorial to fix it. Lemme know if you find more.
