### ISSUE TITLE
There are two conflicting event systems when player enters darts scene.

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#143]
I can find one bug related to this, which is where the player throws the first dart in a game, and the score option menu appears.
@LipglossBPoppin Are we able to delete the one in the Darts scene and it not break anything?

https://github.com/josephcyang4459/Duo-Darts/assets/65678477/868256f0-c747-4a29-98f0-033aeb3b67bf

**Comment by LipglossBPoppin** [comment]
Yes the only event system should be in the singleton, the one in the darts scene probably got added while i was working on the darts game UI.
