### ISSUE TITLE
Tutorial Screens

### ISSUE THREAD

**Issue by DatFluffySheep** [josephcyang4459/Duo-Darts#57]
Add tutorial screens that the player can access and are given at the start of bar gameplay and dart gameplay for the first time. Tim will get screen grabs and write content for these screens. Can just be left as an empty screen and continue button for right now as a skeleton. Tutorials should also be added as options on the pause menu.

**Comment by DatFluffySheep** [comment]
Waitng for art

**Comment by josephcyang4459** [comment]
Tutorial Screen Skeleton is now done in the development branch. Just waiting for art now.

**Comment by josephcyang4459** [comment]
Wait, forgot to add option to view tutorial in the pause menu lol

**Comment by josephcyang4459** [comment]
Here is what the story pause menu and darts standalone pause menu looks like. Lemme know if this looks good. I'm uncertain about how far it should be from the edge of the screen.
![image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/8add1b74-1d14-4592-b2e9-06a121c01a2f)
![image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/0cd4f3de-19f1-4471-b8bd-2ae2e369399b)
