### ISSUE TITLE
Character Name Plate Fonts

### ISSUE THREAD

**Issue by LipglossBPoppin** [josephcyang4459/Duo-Darts#69]
Chad And Jess need new fonts that are either royalty free or public domain.

**Comment by josephcyang4459** [comment]
Here are a few resources that I've found. Not too sure what font we're feeling for Chad and Jess (moody, strong, etc.).

https://www.fontsquirrel.com/
https://fonts.google.com/
https://www.1001fonts.com/

**Comment by LipglossBPoppin** [comment]
I added fonts for chad and jess these can be changed later
