### ISSUE TITLE
Turns not properly updating in dartGame script

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#73]
After 5 turns (player and partner included), the game ends. Current turn only increments when partner's turn is finished, meaning that there are some times when current turn is not properly updated.

**Comment by josephcyang4459** [comment]
For clarification. the maximum amount of turns for a round shows 5, but the current turn only goes up to 3, then the game ends. The game does last 5 turns though (player and partner turns, collectively), though I initially thought that both player and partner would have 5 turns.

**Comment by LipglossBPoppin** [comment]
Changed the UI to better reflect the actual turn count.
