### ISSUE TITLE
[FEATURE REQUEST] A button to click that will show the history of the cutscene dialogue thus far

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#93]
I'm suspecting that some players will accidentally click too fast and miss some dialogue. Having a place where they can view the current and previous dialogue for that specific cutscene would be nice.

**Comment by DatFluffySheep** [comment]
I think this is an awesome feature if you guys on the backend want to make this happen. However, we can save this for a future version for now.

**Comment by LipglossBPoppin** [comment]
The Controls for this are Tab to open log WS to scroll on KBM. Select to open log and Left Stick to scroll on Controller.
