### ISSUE TITLE
Cutscenes Must be Reset Before every build.

### ISSUE THREAD

**Issue by LipglossBPoppin** [josephcyang4459/Duo-Darts#96]
Unity and GitHub have troubles with changes to subscenes so you MUST Resend to Cutscenes before every build.

**Comment by josephcyang4459** [comment]
As a note (mainly for myself), not resetting before every build can cause various characters to not appear during their cutscenes, and probably a few other things too. Refer to #121 and #126. For convenience, here is a snippit of how to reset before every build taken from #121.
![image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/2b5950b8-a8ce-480d-94e3-545be854043e)

**Comment by LipglossBPoppin** [comment]
Pushed a fix for stale data lingering in cutscenes. Should now be fixed.
