### ISSUE TITLE
During Darts Standalone. Hovering on character select buttons do not cause character image to pan into screen

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#98]
Character Images fade in far beyond right of screen rather than into screen.

https://github.com/josephcyang4459/Duo-Darts/assets/65678477/fc4c4019-c1fb-4659-8b6e-ad3fddf8cd33

**Comment by LipglossBPoppin** [comment]
The Game Runs natively at 1920 x 1080, and you have the unity player set to 16x9, which means it is running below native resolution and unless we are planning to release this game with resizable windowed mode there is no bug.

**Comment by josephcyang4459** [comment]
> The Game Runs natively at 1920 x 1080, and you have the unity player set to 16x9, which means it is running below native resolution and unless we are planning to release this game with resizable windowed mode there is no bug.

oh lol. That makes a few other issues make more sense.
